### ISSUE TITLE
Idea/request: _Gyu_ - My Ideas: Settings, Garage, Commands

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#111]
**In the Settings [ F7 ] or in the Garage:**
Add some configurable options and their possible locking.
[ Change Weather, Time, Weather Color, Water Color, Always Day, Always Night ]

**With commands:**
/w [ number ] - Change Weather
/t [ number ] - Change Time
/wec [ hex code ] - Change Weather Color
/wac [ hex code ] - Change Water Color
/day - Always Day Mode ( Lock time in 12:00, reset weather by default )
/night - Always Night Mode ( Lock time in 00:00, reset weather by default )

**Garage:**
Add player name and money ( Like in lobby )
Support more cars [ Sandking, Cheetah ]

**Settings:**
Disable / Enable Water waves sound - ( Sometimes annoying in certain game modes and maps )
Disable / Enable Clouds - ( For a better gaming experience )

**Comment by SkreePy18** [comment]
**/w** - already implemented as **/weather + ID**
**/t** - already implemented as **/st + hour + minutes** 
These two options are permanent, you can reset them by inputting the command without an argument.

**/day** & **/night** will be implemented with the next update, these are also permanent
Colouring the sky and water will most certainly not be supported.

Clouds will be also implemented: **/clouds ** - to turn off & on.

**Garage**
I have added the player's name and money with the latest update. 
To support more cars requires us a modeller which we currently don't have.
