### ISSUE TITLE
Bug: ghousterino - Clan Problem

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#130]
So i deposited with my friend 21k in total to our clan. We tried to request for a clanwar for 0$ and it said that our clan doesnt have enough money. We looked at our balance in clan and our 15k disappeared. I tried to request it again for 0$ and it startet working. Then i tried it again and it again stopped working but our money were gone.

**Comment by SkreePy18** [comment]
You don't request clan wars for $0. Ranked matches: $15k, funwars: $5k. That's the reason of the absence of your money.
