### ISSUE TITLE
Idea/request: DarkyZ - Addition of /nos command

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#136]
Allow the use of /nos command in rooms such as PDD

**Comment by UPGyu** [comment]
**/nos normal
/nos nfs
/nos hybrid**

_https://community.multitheftauto.com/index.php?p=resources&s=details&id=2133
https://community.multitheftauto.com/index.php?p=resources&s=details&id=14305_
