### ISSUE TITLE
Idea/request: _Gyu_ - GhostCars

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#154]
**Add GhostCars to DM and future Race Mode Room.**
The players top1 time car will appear on the screen, and the players own top time car will also appear on the screen. If yours is the top 1 time then only that will be displayed.

**Options:**
Enable or disable Top1 GhostCar.
Enagle or disable your own GhostCar.
Change visibility ( 0-255 )

_https://community.multitheftauto.com/index.php?p=resources&s=details&id=665
https://community.multitheftauto.com/index.php?p=resources&s=details&id=15011
https://community.multitheftauto.com/index.php?p=resources&s=details&id=3799_

**Comment by naouh** [comment]
old feature not planned tbh
