### ISSUE TITLE
Bug: Pajibat - Toptimes not counting in training room solution

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#162]
On certain maps where anti short-cut measures are added, i.e obstacles on road that are removed if you complete previous parts are the reason for some toptimes not counting. If you complete the part and then warp back the obstacles don't reappear and you're unable to pass checkpoints. If you make a clean (no warp) run in that same session without rejoining arena, your hunter toptime won't count

**Comment by naouh** [comment]
fixed
