### ISSUE TITLE
Bug: _Gyu_ - Some Buggs 2

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#164]
**Speed Power:**
Hey I remember someone reporting a bug a long time ago when the Speed Power didnt work on the PDD, and I can confirm that this happened to me with the cheetah car. Unfortunately I dont have a video of this.

**Map Downloading:**
The downloading did not start (?) after starting the map I fall into the water and die. The white screen always appeared on the next map.

![mta-screen_2022-09-25_20-46-30](https://user-images.githubusercontent.com/112903361/193110360-d89145a5-2ad5-4a76-a0d3-e305798f020b.png)
![mta-screen_2022-09-25_20-46-32](https://user-images.githubusercontent.com/112903361/193110366-d1d775b2-8a19-44cf-8023-cb0422672e43.png)
![mta-screen_2022-09-25_20-46-55](https://user-images.githubusercontent.com/112903361/193110372-29df6a84-b33a-428b-8ad1-af0b11c578a9.png)
![mta-screen_2022-09-25_20-47-01](https://user-images.githubusercontent.com/112903361/193110377-15a01705-8c6e-4663-b832-312ba71db71d.png)

**PDD Power Position Problems:**
I know some have already reported I just show screenshots of there all. ( Spikes, Barrel, Oil )
![mta-screen_2022-09-26_12-43-54](https://user-images.githubusercontent.com/112903361/193110611-f72e0be3-971f-4771-ba23-b8915589e4ab.png)
![mta-screen_2022-09-26_12-44-48](https://user-images.githubusercontent.com/112903361/193110620-9d9c2d52-5bfe-4138-92b9-e5de481e08d4.png)
![mta-screen_2022-09-26_12-53-00](https://user-images.githubusercontent.com/112903361/193110624-66d829b1-6c66-45c1-a7f9-0806ad4f0f1d.png)
![mta-screen_2022-09-26_12-53-02](https://user-images.githubusercontent.com/112903361/193110628-e78cb2e8-85cd-46a3-a35d-6d2f1796f529.png)

**Scoreboard Issue:**
Scroll down the scoreboard and the team names will change color.
![mta-screen_2022-09-28_19-30-45](https://user-images.githubusercontent.com/112903361/193112689-3740969e-4372-47aa-a6ed-ea11814b1e4c.png)
![mta-screen_2022-09-28_19-30-48](https://user-images.githubusercontent.com/112903361/193112694-4f5640d2-6ef9-4c5f-bea5-2c4a8f75137c.png)

**PDD Power Icon Disappearing:**
![mta-screen_2022-09-26_21-48-06](https://user-images.githubusercontent.com/112903361/193112793-c374c5e6-8f5e-4ff8-9aaf-020902157cce.png)
![mta-screen_2022-09-26_21-48-09](https://user-images.githubusercontent.com/112903361/193112800-f96582a3-d06c-4263-8ebd-9998a3a164bb.png)
![mta-screen_2022-09-26_21-48-27](https://user-images.githubusercontent.com/112903361/193112803-8479d879-0f15-4092-80ed-ba95ea8ce2db.png)
![mta-screen_2022-09-26_21-48-33](https://user-images.githubusercontent.com/112903361/193112807-c111ce64-6bcf-4d63-b784-ccfb83657261.png)
![mta-screen_2022-09-26_21-48-37](https://user-images.githubusercontent.com/112903361/193112813-0abb60fd-6461-49b5-90e8-576347e25761.png)
![mta-screen_2022-09-26_21-48-44](https://user-images.githubusercontent.com/112903361/193112821-3f048979-829d-4a63-8082-e41a2d9e8ae4.png)
![mta-screen_2022-09-26_21-48-49](https://user-images.githubusercontent.com/112903361/193112823-b672ef47-3b55-40cd-a512-cb11865a78f8.png)
![mta-screen_2022-09-26_21-48-40](https://user-images.githubusercontent.com/112903361/193112817-3665967a-2713-4233-81b7-84e5035ecb09.png)

**Reporting Map Problem:**
![mta-screen_2022-09-29_19-55-10](https://user-images.githubusercontent.com/112903361/193113237-f590d117-689f-4475-9a81-e3dca7c54daf.png)
![mta-screen_2022-09-29_19-55-15](https://user-images.githubusercontent.com/112903361/193113244-f180f325-014f-4102-9648-d2bed6e5940d.png)
![mta-screen_2022-09-29_19-55-16](https://user-images.githubusercontent.com/112903361/193113249-1baaa7fe-a066-4c5d-a8c8-a05730a23349.png)
![mta-screen_2022-09-29_19-55-18](https://user-images.githubusercontent.com/112903361/193113252-fe11b3d5-c353-4b01-94e7-2f598d6aa479.png)

**Comment by SkreePy18** [comment]
Some parts are implemented, but others cannot reproduce. We cannot track the issues properly because there are 20 bugs in one ticket.
