### ISSUE TITLE
Enhancement: New PDD powers [lead ticket]

### ISSUE THREAD

**Issue by SkreePy18** [MTASA-TFF/The-Favoured-Few#172]
***Lead ticket of new PDD powers***

Issue: #157 
**Bomb** - The bomb from Catch mode, when you touch your opponent the timer count back from 30 seconds. Players can pass the bomb to others after the time ends the player explode.

**Ramp** - Spawn a Ramp behind your car for 5 seconds. [ ID: 1634 ]

**Hay** - Spawn a Haystack behind your car. [ ID: 3374 ]

**Mine** - Spawn a Mine behind your car. [ ID: 2918 ]

**Ramp Car** - Put Ramps in front and behind your car for 5 seconds. [ ID: 1634 ]

About old Powers:
Drunk - Bring back the old Drunk Power with more camera shakes.
Flashbang - Change the full white screen to Black and White effect with Blur Shader.

Issue: #137 
a rare power that player will place on the map, the bomb will have countdown and when the countdown ends all players in short range will blow up, all players in medium will get flashbang effect and knockback (maybe spin if knockback is hard to code), all players in long range will have flashbang effect shorter than those in medium range. The power should be too rare as it is very op. (More rare than the rocket , maybe % of rocket)

Issue: #129 
**No Brakes** - If you touch your opponent, the brakes of his vehicle will not work for 5 seconds, and his vehicle is constantly accelerating.

**Reverse** - If you touch your opponent, his vehicle will turn back 180°.

**Sweeper** - Fire a Sweeper vehicle at high speed like a rocket.

**Fake** - Put it down just like a barrel or oil, if the opponent picks it up it doesnt give him anything... ( playing funny sounds - laughing or farting XDD )

**Sticky** - If you hit the sticky stuff it will slow down your vehicle.

**Clone** - Create a clone of the currently used vehicle with the player name and health.

Issue: #120 
add some negative powers that automatic start such as puncture ,exchange positions with one of opponents,spinning,burning

Issue: #118 
decoy cars :
player will place copy of his car on (would be better if there is name on top of it)
copy enemy car:
player will have the same car with enemy he touched
steal enemy power:
player will steal the power of enemy he touched
(maybe) small spinning ball around player:
player will have small spinning ball for a short time once activated, the ball can move enemies
laser:
laser from frontlights , laser will eat car's health quickly
invisible car:
player will be invisible for a short time

possible improvements:

magnet:
instead of enemy sticked to right side, make it dynamic (enemy sticks to player where it was hit from)

**Comment by UPGyu** [comment]
**Change Shield power or make a new one called Protection.**

**Change the Shield Power for protecting you from everything for _xy_ seconds.**
_( Crashes and Explosions, Flip, Rocket, Gravity, Flashbang, Spikes, Ignite, Magnet, Barrel, Oil and from the future new powers )_
**If your opponent touches you, his Power is not activated and he loses it.**

_( Maybe play a short sound when you take up, use or placed Powers )_

Imo this power ideas is too much or bad for PDD:
https://github.com/MTASA-TFF/The-Favoured-Few/issues/120 - No.
https://github.com/MTASA-TFF/The-Favoured-Few/issues/137 - No. Too much for PDD.
https://github.com/MTASA-TFF/The-Favoured-Few/issues/118 - Steal Enemy Power: I dont think its possible... **_( Maybe it would be better if the opponents Power starts automatically and starts on their own vehicle. )_** - The Power name " **_Play_** or _**Hack**_ "
Small Spinning Ball: I dont think its good idea.
Laser: No. Same with Ignite...
Invisible car: Similar with Ghost, I dont think so...

_My goal is not to blame other players ideas, I just gave my opinion._
