### ISSUE TITLE
Bug: _Gyu_ - Global Notifications Make FPS Drop

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#174]
Massive FPS Drop after CWs finished.

![mta-screen_2022-10-07_16-23-24](https://user-images.githubusercontent.com/112903361/194577372-f780d991-d09e-484b-8ab4-9c332cd42bb8.png)

**Comment by SkreePy18** [comment]
It is not caused because of the notifications but the way of handling the end of clanwar itself. We do believe, with the next update it will be solved.
