### ISSUE TITLE
Idea/request: _Gyu_ - Change Effects Colors

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#176]
**Possibility to change the color of some effects:**
White Smoke, Black Smoke, Fire, Brake trace, Rubber smoke, Exhaust gas.

**About the Rocket:**
Turn off the white blinking light or change the color to the same as that which can be set via the garage.

![mta-screen_2022-10-07_17-56-56](https://user-images.githubusercontent.com/112903361/194599386-a6dd2c9c-9929-4f3f-9327-6217a7fffe6a.png)
![mta-screen_2022-10-07_17-57-10](https://user-images.githubusercontent.com/112903361/194599393-1d944891-fef0-4e89-b2c5-9c79bf3fb7c9.png)
![mta-screen_2022-10-07_17-57-15](https://user-images.githubusercontent.com/112903361/194599401-f80fbe9b-11eb-4509-9b7c-1b7404c7b663.png)
![mta-screen_2022-10-07_17-57-42](https://user-images.githubusercontent.com/112903361/194599407-0addb4b7-5d14-4de5-953a-c7a6956ea2ff.png)
![mta-screen_2022-10-07_17-58-41](https://user-images.githubusercontent.com/112903361/194599411-085b4e5c-d33f-464c-8624-691150cb0ec2.png)
![mta-screen_2022-10-07_18-09-08](https://user-images.githubusercontent.com/112903361/194599417-d82db2c9-f605-4b48-b0cc-b85e2f4c73c6.png)
![mta-screen_2022-10-07_18-09-09](https://user-images.githubusercontent.com/112903361/194599422-c30e5fbe-d017-48f4-919b-1137a9eedb6f.png)
![mta-screen_2022-10-07_18-10-05](https://user-images.githubusercontent.com/112903361/194599431-519ca94a-b5fb-4cee-b148-d6cb4845d4c0.png)
![mta-screen_2022-10-07_18-10-06](https://user-images.githubusercontent.com/112903361/194599436-91a00294-635b-42ff-aa9b-3801a09c384c.png)
![mta-screen_2022-10-07_18-10-07](https://user-images.githubusercontent.com/112903361/194599448-8507d318-1325-42f2-bc1d-f491796202fb.png)

**Comment by SkreePy18** [comment]
Effect colours cannot be changed so easily, it requires .fx files which can cause FPS drops easily.
