### ISSUE TITLE
Bug: _Gyu_ - Maps Downloading Problem

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#177]
Sometimes the downloadings not started or very slow? ( Missing Map Downloading GUI )

![mta-screen_2022-09-30_21-28-29](https://user-images.githubusercontent.com/112903361/194637045-7ef28613-3198-4d09-a1c8-93cbe7ed622b.png)
![mta-screen_2022-09-30_21-30-02](https://user-images.githubusercontent.com/112903361/194637048-4bee75aa-59b9-44e9-81c2-ef01aaaf96af.png)
![mta-screen_2022-09-30_21-30-06](https://user-images.githubusercontent.com/112903361/194637049-7f2af8d9-87ab-4b1f-8055-89439a9034f9.png)
![mta-screen_2022-09-30_21-30-08](https://user-images.githubusercontent.com/112903361/194637054-f387ce44-f015-4b44-9800-6996daf9a439.png)

**Comment by naouh** [comment]
this is because your internet is too slow

**Comment by UPGyu** [comment]
I cannot agree with this reason, my internet connection is fast and stable, but okay. 

![Névtelen](https://user-images.githubusercontent.com/112903361/203136237-c3d52cf0-b354-4fa2-b7f5-0f3e008e27e3.png)

**Comment by naouh** [comment]
It happened only once or ?

**Comment by UPGyu** [comment]
Nothing like that has happened to me recently, but I havent been very active lately. I seem to remember that this problem occurred when I deleted the resources folder. So I think this problem can happen with newbies whos are entering the server for the first time.
And these only occurred on maps using custom objects.
