### ISSUE TITLE
Enhancement: Increase map buy-time limit

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#186]
Issue opened by **DarkyZ**

What the title says, people keep buying the same map over and over again, due to the low cool-down times for both buying maps and map's cool-down itself. 

I'd recommend increasing map buy cool down to 30-35mins, and map's cool down to 1 hour minimum.

**Comment by naouh** [comment]
Wont for now hdm players seems happy with this atm
