### ISSUE TITLE
Enhancement: _Gyu_ - Some Ideas

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#188]
**Pressed Keys Script:**
Good for spectetating players in DM mode.
_https://community.multitheftauto.com/index.php?p=resources&s=details&id=11372_

_**( Maybe )**_
**Countdown in chat:** _( Good for DD mode, sometimes players in 1v1 want face to face. )_
The command allowed only for alive players in 1v1.
_https://community.multitheftauto.com/index.php?p=resources&s=details&id=7271_

**Add possibility to open the user panel in the lobby.**

**Comment by SkreePy18** [comment]
No place for it, and some people might don't want others know their trick on WFF maps.
On the other hand, multiple issues in 1.... Closing this ticket
