### ISSUE TITLE
Bug: _Gyu_ - Two bugs

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#189]
**The Lobby update bug is still here.
The bug after you die from explosions sapwn in ground zero is still here.**

https://github.com/MTASA-TFF/The-Favoured-Few/issues/179
https://github.com/MTASA-TFF/The-Favoured-Few/issues/155

![mta-screen_2022-10-12_20-30-21](https://user-images.githubusercontent.com/112903361/195422652-01016dc6-5375-4013-a41a-cada4dec8fd3.png)
![mta-screen_2022-10-12_20-30-23](https://user-images.githubusercontent.com/112903361/195422658-9de92b80-0bb5-44c7-b12e-984baede55df.png)
![mta-screen_2022-10-12_20-30-24](https://user-images.githubusercontent.com/112903361/195422660-791effd0-5335-437d-80a3-80156724c507.png)
![mta-screen_2022-10-12_20-30-31](https://user-images.githubusercontent.com/112903361/195422665-6cd9b810-d912-4b9e-bb77-4f99a41a6f76.png)
![mta-screen_2022-10-12_20-30-54](https://user-images.githubusercontent.com/112903361/195422671-c489bd62-2590-4359-a904-1e3f63ada51c.png)
![mta-screen_2022-10-12_20-34-41](https://user-images.githubusercontent.com/112903361/195422678-b0dd609c-a629-4b51-92dc-e6837200f335.png)
![mta-screen_2022-10-12_20-34-43](https://user-images.githubusercontent.com/112903361/195422681-086f000e-7b4c-4acf-b311-eb60427bc1bf.png)
![mta-screen_2022-10-12_20-34-47](https://user-images.githubusercontent.com/112903361/195422686-bd66099c-8a82-4f60-af74-6acc05794451.png)

**Comment by naouh** [comment]
For the lobby if you are afk in and go to desktop it doesn't refresh properly events
