### ISSUE TITLE
Enhancement: _Gyu_ - Training After Die

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#191]
After you die in the public rooms ( Hunter, Destruction Derby, Shooter, Catch, Etc... ), you can press enter, to respawn and play with the other dead players if you dont feel like being in spectator mode.
Ofc, kills or top times do not count in this training mode.

**Comment by SkreePy18** [comment]
It is useless and we cannot dedicate extra time for such things.
