### ISSUE TITLE
Bug: _Gyu_ - PDD Power Icon Or Map Bug

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#192]
**PDD Power Icon Disappearing:**
_This bug seems to occur only on maps using custom objects...
MineCrash 1 and 2
MarioCrash 1 and 2_

![mta-screen_2022-10-13_13-16-26](https://user-images.githubusercontent.com/112903361/195585050-308ec76f-d8a3-49d1-aca4-94cc409b5f4b.png)
![mta-screen_2022-10-13_13-16-29](https://user-images.githubusercontent.com/112903361/195585058-d941b8d3-fb0b-44be-9651-b4127d457e65.png)
![mta-screen_2022-10-13_13-16-34](https://user-images.githubusercontent.com/112903361/195585063-52af72eb-2f88-44f0-a60a-b8fc89b6546a.png)
![mta-screen_2022-10-13_13-16-37](https://user-images.githubusercontent.com/112903361/195585069-6d28b076-9500-447e-af8e-ccf15ae51d8e.png)
![mta-screen_2022-10-13_13-16-48](https://user-images.githubusercontent.com/112903361/195585074-4184da73-d16e-4602-a167-f9c052a1df11.png)
![mta-screen_2022-10-13_13-16-58](https://user-images.githubusercontent.com/112903361/195585078-963b98e5-7a79-4909-b6a6-cd867f0da079.png)
![mta-screen_2022-10-13_13-17-06](https://user-images.githubusercontent.com/112903361/195585084-a56e04c0-dff4-4d51-9219-52228b177e8d.png)
![mta-screen_2022-10-13_13-17-12](https://user-images.githubusercontent.com/112903361/195585091-9eb6d1b7-44ee-478d-99bf-05d3b592d98a.png)
![mta-screen_2022-10-13_13-17-19](https://user-images.githubusercontent.com/112903361/195585098-286438c7-f70d-4369-95db-23878cddc71d.png)
![mta-screen_2022-10-13_13-17-23](https://user-images.githubusercontent.com/112903361/195585106-c1ae3557-a81a-45e4-a33c-ae986d73aaf2.png)

**Comment by naouh** [comment]
Prob the map causing this issue, will delete the map

**Comment by naouh** [comment]
Ok after a test it work fine for me :(
