### ISSUE TITLE
Enhancement: _Gyu_ - Changes In DrawDistance or Clouds Command

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#196]
addEventHandler ( "onClientResourceStart", resourceRoot, 
    function() 
        for i = 1, 10000 do -- Put all objects between 1 t/m 10000 in a loop 
            engineSetModelLODDistance ( i, 300 ) -- Force them to load. 
        end 
    end 
) 

addEventHandler ( "onClientResourceStart", resourceRoot, 
	function() 
		setFarClipDistance ( 1500 ) -- We adjust visibility range on 3000 metres 
	end
) 

addEventHandler ( "onClientResourceStart", resourceRoot, 
	function() 
		setFogDistance ( 1500 ) --	Set the fog distance to 500 units, so any weather will appear to be extremely clear
	end
) 

addEventHandler ( "onClientResourceStart", resourceRoot, 
	function() 
		setCloudsEnabled ( false ) 
	end 
) 

--

**The first one is change every **ModelLODDistance** so its can make weird things in default GTA:SanAndres Map but i think its good for MTA Maps...**

--

**Comment by naouh** [comment]
Well clouds are disabled by default, draw distance is already editable in f7 settings and fog same its not used on our server
