### ISSUE TITLE
Enhancement: _Gyu_ - ClanWar Rooms

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#197]
**Distinguish clan war rooms with different colors and icons, even if there is no running clan war.**

![mta-screen_2022-10-13_14-18-15](https://user-images.githubusercontent.com/112903361/195594062-320a3d99-8508-4ddb-aed6-2e1d8ea13f9c.png)
![mta-screen_2022-10-13_14-18-31](https://user-images.githubusercontent.com/112903361/195594069-6afa7d6a-368d-453c-9cf3-08b2d6b6e1c4.png)

**Comment by naouh** [comment]
Will add special icons instead of event ones for clanwars

**Comment by naouh** [comment]
![image](https://user-images.githubusercontent.com/62722816/199320229-c70813ec-d4fc-4136-8f25-5260095e2bc2.png)
