### ISSUE TITLE
Bug: _Gyu_ - Death In The Water

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#198]
https://github.com/MTASA-TFF/The-Favoured-Few/issues/178

![mta-screen_2022-10-13_16-56-42](https://user-images.githubusercontent.com/112903361/195639286-893f7ba9-cf35-4f49-86f8-6a94b1e4d16b.png)
![mta-screen_2022-10-13_16-56-51](https://user-images.githubusercontent.com/112903361/195639296-f15e21b9-054b-4157-9fc4-67ea5195ae50.png)

**Comment by SkreePy18** [comment]
It can happen at special occasions, it is related to MTA not server.
