### ISSUE TITLE
Bug: _Gyu_ - Lotto

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#208]
**The lotto game costs 5.000 in 10 minutes, then 7 and 4 minutes for only 2.000**

![01](https://user-images.githubusercontent.com/112903361/195869158-9a3275c6-159c-4356-bcd8-722ed1bde39b.png)
![02](https://user-images.githubusercontent.com/112903361/195869154-dcb279ec-4c33-461c-b892-3d65f125e597.png)

**Comment by naouh** [comment]
Output only its fixed price was 2000$ already
