### ISSUE TITLE
Bug: Wrong Country Flag

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#210]
Issue opened by **Ben_-Sage**

Peru and Austria flags are wrong in clan menu. If you want to see an example, check Men for All Seasons clan and view members. SazukE is from Peru, yet his flag is showing as Austria.

**Comment by naouh** [comment]
Flags are good can you make him reconnect to see if it get fixed ?

**Comment by naouh** [comment]
Need to join forum once to fetch correct country :)
