### ISSUE TITLE
Bug: _Gyu_ - User Panel

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#211]
**Missing Home and Premium Pages**

![mta-screen_2022-10-14_20-35-47](https://user-images.githubusercontent.com/112903361/195926144-bd482f48-f4d0-4abb-8f1b-04ce7be46772.png)
![mta-screen_2022-10-14_20-35-51](https://user-images.githubusercontent.com/112903361/195926150-3494ca1e-3c85-4927-a3b8-494a39e2baac.png)

**Comment by naouh** [comment]
Fixed
