### ISSUE TITLE
Bug: _Gyu_ - User Panel Settings Notifications

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#213]
**Some settings are missing notifications when you turn on or off.**

**Comment by naouh** [comment]
Title
Supernick

**Comment by UPGyu** [comment]
> Title Supernick

What do you mean?


Btw as i said some notification is missing and some have other colors like red-green-orange.

I think you should use the same pattern as I mentioned here ( https://github.com/MTASA-TFF/The-Favoured-Few/issues/212 ). If you turn something on, the notification color should be green, if you turn something off, the notification color should be red.

**Comment by naouh** [comment]
added to next update
