### ISSUE TITLE
Bug: Disappearing members list

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#240]
Issue opened by **Aywy**

Whenever I change someone's rank in my team, the whole members list disappears, making it unusable. Sometimes multiple people's rank change all at once.

**Comment by SkreePy18** [comment]
Regarding rank changes, it is caused because when you change the rank of a member, the members table gets reordered and if you spam it will cause you promote/demote someone you didn't want to. In case of a disappearing member list, we are checking
