### ISSUE TITLE
Enhancement: _Gyu_ - User Panel And Scoreboard

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#244]
**When you open the User Panel or the Scoreboard, fade out the background in the Lobby.** 

![mta-screen_2022-11-11_09-43-05](https://user-images.githubusercontent.com/112903361/201301274-8a9860a6-af68-40fe-8533-deab0852cc88.png)

![mta-screen_2022-11-11_09-42-46](https://user-images.githubusercontent.com/112903361/201301268-6272467d-ec0a-4f0a-b96e-c8993d2d1064.png)

**Comment by SkreePy18** [comment]
Just enabled blur option in userpanel. It was removed from scoreboard because it even caused even more lags...

**Comment by UPGyu** [comment]
> Just enabled blur option in userpanel. It was removed from scoreboard because it even caused even more lags...

Its enabled in the screenshots, but not working. Btw i think its more useful if its default in the lobby (only in the lobby).
