### ISSUE TITLE
Enhancement: Hunter Suggestion

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#247]
Issue opened by **NetriX**

I dont remember if it was this srv or another but i remember there was a hunter room with respawn available and it was much better for starters to focus on learning hunter or just have fun in general, like a small ffa match like cod wouldnt hurt anyone would it :D?

**Comment by naouh** [comment]
Yes we could add but we already have some many rooms almost empty adding one more resource is not worth for the moment maybe later

**Comment by naouh** [comment]
Wont be added for now maybe later :)
