### ISSUE TITLE
Bug: Pressing 'load warp' registers as warp loaded

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#257]
Issue opened by **xSimas**

How to reproduce: 1. Go to training, select easy mapazo. 2. Don't save any warps. When you get close to hunter, press the "load warp" key. 3. Take hunter. No toptime GG = cuz the system thinks that you used a warp even though you didn't have any saved.

**Comment by naouh** [comment]
Fixed if you don't have any warp saved it wont happen anymore
