### ISSUE TITLE
Enhancement: new mode for serve

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#258]
Issue opened by **zenotsyne**

Prop's and Hunters will be good mode for serve

**Comment by naouh** [comment]
i don't understand please reopen with more details.

**Comment by UPGyu** [comment]
I think he meant **Prop Hunt** **_( Hide and Seek )_** mode.
I have already sent this idea privately to Skreepy earlier.
