### ISSUE TITLE
Enhancement: Training Checkpoint System

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#260]
Issue opened by **Atomix**

Currently if you create a checkpoint on a map, it shows you the time it took you from spawning until reaching the checkpoint.

Problem is, that we can't train specific parts with this system while using warps.
It could be useful that, if you load a warp, it shows the time it took you from loading the warp until reaching the checkpoint.

**Comment by naouh** [comment]
its live already :)
