### ISSUE TITLE
Bug: server has lot of stutterings

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#263]
Issue opened by **veni**

Since I came from work (June 3rd 2022) I never encountered lag/stutterings on this server, now after these bullshit updates I've got for first time on this server a lot of stutterings. I see a lot of players having it too, for me it's the first time I get this problem on that server.
Please fix.

**Comment by naouh** [comment]
if you dont want 'bullshit updates' go to a server noone take care of then u won't see any updates :)
