### ISSUE TITLE
Bug: _Gyu_ - Little Issue With The User Panel

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#266]
If I open the user panel and then open the console, the two icons will be visible.

![mta-screen_2022-11-29_23-12-58](https://user-images.githubusercontent.com/112903361/204661103-d40da2b6-277a-4486-9a35-de72bdde2d0b.png)

**Comment by SkreePy18** [comment]
It's not a bug. PostGUI is enabled for them otherwise wouldn't be visible.
