### ISSUE TITLE
Enhancement: Delete bikes from pdd

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#287]
Issue opened by **Nipy**

people just runs forever for good powers with bikes, i believe it is best if we remove them all

**Comment by UPGyu** [comment]
I support the idea and would add a few more vehicles to this list:
_Name - ID_



**Bikes:**
Pizzaboy - **448**
PCJ-600 - **461**
Faggio - **462**
Freeway - **463**
Sanchez - **468**
BMX - **481**
Bike - **509**
Mountain Bike - **510**
FCR-900 - **521**
NRG-500 - **522**
BF-400 - **581**
Wayfarer - **586**
HPV1000 - **523**
Quadbike - **471**



**Duplicated vehicles:**
Boxville Mission - **609**
Damaged Sadler - **605**
Damaged Glendale - **604**
Monster 2 - **556**
Monster 3 - **557**

**Comment by naouh** [comment]
removed
BMX - 481
Bike - 509
Mountain Bike - 510 from all maps
