### ISSUE TITLE
Enhancement: Ability to scroll using mouse in Garage > Paint (and wherever applicable)

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#302]
Issue opened by **Anarch1st**

Title: Ability to scroll using mouse click in Garage > Paint (and wherever applicable)
Description: As the title says, add the ability to scroll using the scroll bar with mouse click in the Garage option GUIs

**Comment by KRKDEV** [comment]
This has been resolved in upcoming garage update.

**Comment by SkreePy18** [comment]
Will be unnecessary for new garage, marked as `won't do`
