### ISSUE TITLE
Bug: _Gyu_ - PDD: Reverse Power

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#303]
If I touch my opponent with " Reverse " power, for some reason he doesnt turn around but my vehicle does.

https://github.com/MTASA-TFF/The-Favoured-Few/issues/172
**Reverse - If you touch your opponent, his vehicle will turn back 180°.**

**Comment by naouh** [comment]
Well i tested and it work perfectly, only case could be he had reverse too.
