### ISSUE TITLE
Minigames Bugs lead ticket

### ISSUE THREAD

**Issue by naouh** [MTASA-TFF/The-Favoured-Few#310]
RCR:

Blue: R: 0 - G: 0 - B: 255 - Alpha: 153 = random ground vehicle
Yellow: R: 255 - G: 255 - B: 0 - Alpha: 153 = random sea vehicle
Red: R: 255 - G: 0 - B: 0 - Alpha: 153 = random air vehicle
**Any other color will count as a checkpoint but won't change the vehicle.** - THIS NEED TO BE FIXED
Remove combine harvester.

RPR:

When your vehicle explodes once, it will keep blowing up every time you respawn.
Need to edit the spawn should be a timer and not first marker hit, to disable ghostmode.

WARE:

Rounds bug round moved to 32 for non reason.
Boss game need carhide.

CD:

Rockets stay sometimes need clear elementdata at the end.

Global:

Peds sometimes invisible.

RTB: 

Peds issues under the map the bomb following them i guess.

RCD:

Marker doesn't spawn sometimes.

PH:

Finish spectator restrictions.
Sometimes need spam click to transform.
Auto transform if not transformed before hunters spawn.

FALLOUT DUNE:

Should dissapear faster

DRAGON:

Should be faster in beginning and increase with time but not too fast instant.

Topwins:

Return error at loading sometimes, doesn't work in DZ.

Selection:

Some gamemodes appear rarely, make 4th option to redo.

**Comment by UPGyu** [comment]
Hey, some suggestions from me: **( RIP Skreepy )**
Maybe some already fixed or there idk. And i not added removed modes, Need test them again.


**GunGame:**
Respawn not work ( after restart the room problem solved )
Missing Lvl up sound
Remove rifle weapon lvl
Missing weapons reload script with " R " key 


**Random Car Race:**
Idk if its global or not, but after rcr map started and someone joined later after we finished the map the timer stop in 00:00:00 and the vote not change the mode.
Disable vehicle weapons
If you die with helicopters after respawning your rotors not working
RCR respawn change to 3 sec
RCR Spectetating: You cant see the current cp
Make changes in random car script you cant get again the same vehicles


**Fallout: Dune**
Dune: Too big map ( remove green colored objects ) Or make the objects faster falling
Add some random powers:
Jump, Boost, Magnet, Gravity, Rocket, Ghost, Spawn Spinning Dune on a random player 


**Fallout Ped:**
Add some random powers:
Gravity off for 10 seconds (after on), 1 Rocket, Spawn Spinning Dune on a random player, Spinning a random player 


**Global MiniGames:**
 - Remove Clan Colors
 - Race based modes have bad respawn system ( Make like default race mode - Position, Speed, After you die twice fast in same CP move back -1 cp or make spawn protection in respawn too )
 - Change respawn times in all modes to 3 seconds from 5 expect Random Power Race
 - Markers and CPs always flickering in every modes
 - If ghostmode allowed in the current mode you can allowed to use car-ped hide ( -Tron, -RPR )
 - Add healt bar for every modes where you playing with ped and weapon icons with ammo where you can get weapons
 - Fix spawn positions add for every modes more thank 32 spawn points and dont allow spawn two players in same positions - respawns too if afk players spawned somewhere others dont allow to spawn there
 - Fix giving points. In race based modes only players got points whos finished the map others not.
 - Fix win steaks after every win steak add double points
 - Add respawn protection where you can allowed to respawn: For 5 second ghost mode enable and players cant hit you. You can move but if you start aiming or shooting ( example: gun game your protection is removed )
 - Missing AFK Warnings and kicks
 - Sometimes when the modes fast finished missing votes, so next mode is random
 - After modes ended missing podiums ( show the first 3 peds in podiums for some seconds like in ffs - maybe CAT can make a good custom podium )
 - Missing kill msg script
 - Missing Achievements ( Playing rounds, Wins, etc-idk )
 - Some modes have only one map like Avalanche or Color Dash, so under the radar and in the chatbox write the full mode name only like [ Color Dash ] [  Ware ] [ Avalanche ] [ Glass Bridge ] [ Red light, Green light ] etc 


**Jump:**
Sometimes the jump not working... ( Need reconnect for make work again )
After you die you can use jump in spectetating
Change the keys:
Right Click - Big Jump
Left Click - Normal Jump
ALT - Nos
Add a new UI like in SW 


**HAY:**
Sometimes the hay model duplicated? or idk... Maybe the mode started twice? The hay stack sometimes inside eachothers...
Move the mode near the water... If you fall in the water you die.
In zero position vehicles can spawn and you can enter them with F or G key <--- Its a global problem imo 


**CUBE:**
Rework the model movement and add back " Cheese " map ( maybe spawn only inside the cheese )
Add more maps: ( And maybe rename the mode name to " Moving platforms " or something )
 - Tilt ( By: tma ) https://community.multitheftauto.com/index.php?p=resources&s=details&id=39
 - Circles ( By: eXo|Dragon ) https://community.multitheftauto.com/index.php?p=resources&s=details&id=18801 
 
 
**Tron:**
After the countdown has ended, make the NRG auto move and after 3 seconds the lines will appear 


**Sweeper War:**
Add new UI for shooting and jumping something like ffs version
Sometimes you can shoot yourself ( make your own sweeper ghost mode just for you )
After 15 seconds remove the used sweepers ( not with explosions ) 


**Avalanche:**
Need make a new map and new spawn points ( Under the spawn make a hole so vehicles can fall in the water and faster removed )
Need remove the event for the player try enter the vehicles with F and G key ( Sometimes you can enter a vehicle ) 


**Color Dash:**
Missing colors text from the cube
After Color Dash mode players still have rockets - confirmed
After you took rocket item show it on your screen with ammo numbers
+ You can took more than one rocket
Add rocket in every rounds
Change the CTRL to Mouse Left to shot a rocket 


**Danger Zone:**
Dont place the marker in the same place again
Make the marker color RED if you are out and GREEN if you are in ( in spectetator not working the color changes )
No more random winners if no one enters the marker - your distance to the marker counts, so whoever is closer to the marker is the winner
Use only repair pickup for place markers ( no peds no nos ) 


**Random Power Race:**
On custom objects? ( Tampon maps ) placed oil, barrel and spikes are invisible
 - Spikes invisible but work
 - Oil inv and not work
 - Barrel inv and not work
 - After the mode finished remove these objects and remove rocket too from your car ( Maybe there bugged too not just in Color Dash )
 - Disable Carhide 


**Dragon:**
Add custom models and rename the mode
Fix the objects flickering ( The first and the last platforms )
Its possible to finish the mode, after a time the Dragon is stop moving ( I saw CAT and Mrash do it )
Add kill script before you fall in the water
Replace the bike to NRG
Change the movement speed ( too slow start and too fast finish ) 


**Glass Bridge:**
CAT want make new map with custom objects
Its possible to laggers not fall down when they spamming space and run ( So need fix this or make a new map maybe disable running )
After the round started dont let spawning the joined players ( After lose your lifes you can play again after reconnect ) 


**Red light, Green light:**
CAT want make a new map with custom objects
Need changes with the lights ( Imo remove yellow light )
Missing sounds ( Red light and Green light, maybe add shooting sound when you die )
Sometimes when the light is changed from yellow to red and you stop moving but the animatin not ended you not die

**Comment by UPGyu** [comment]
**+1**
**Fallout Ped:**
Idk if it is the same as the Dune version, but I guess. Change the end of the game. Make all the objects in the round falling down. Currently at the end of each round there are 3 platforms left that dont fall off. That way more winners are possible and as long as they dont die the round doesnt ending.

**Comment by UPGyu** [comment]
**MiniGames Global:**
Btw, idk why the explosions is globally disabled I think its need disable in **Danger Zone** only when you are out of the marker and in **Tron** when you hit the line.

And theres also a problem when you leave MiniGames room and join another room, interesting things happen. Players spawn without cars, or spawn to a completely different location on the map, and it also happened that in DM room the player had a rocket, etc

**Comment by SkreePy18** [comment]
- For fallout, all objects will fall down, doesn't matter the mode.
- Achievements added already. **Next time you open up an issue check before doing it...**
- If you plan to make a custom model map **ALWAYS USE THE OBJECTS WHICH ARE ON THE MAP. e.g.: Dragon. I am not going to add it until**
- Cheese map is not practical, it is very hard to play on it, either fix or won't be added back
- Duplicating hay models are because of movement of them
- Color Dash: Rockets won't have ammo at all..
- Spawnpositions: I don't see the point of having 32 spawns on map where its not necessary
- Hay won't be moved
- 'R' is not planned to be added
- Respawn will stay 5 sec as it is
- Level up sounds are useless and only taking space
- We plan to keep Sancher for Dragon as well, easier control in regards of turning
- Text won't be added on Cube, as it is quite simple at this point, what is might considered is adding it to the screen.

Rest bugs are being worked on.

**Comment by UPGyu** [comment]
**Glass Bridge:**

The same happened with this mode as with the HAY mode. The glass panels are duplicated so you cant fall off unless both time have the "wrong" glass.

**Comment by UPGyu** [comment]
Some Bugs:


Dragon on Color Dash:
![mta-screen_2023-02-15_13-18-15](https://user-images.githubusercontent.com/112903361/219025859-339d621a-380e-46e1-938f-ba219efc60da.png)
![mta-screen_2023-02-15_13-18-43](https://user-images.githubusercontent.com/112903361/219025865-211de3df-692a-4d3c-8a9a-bb36b48dc0ac.png)


Player leave MG room and joined to DM and this happened with the progress bar:
![mta-screen_2023-02-13_17-50-31](https://user-images.githubusercontent.com/112903361/219025978-8fd7d68f-00d5-4b16-ac85-cd9ee972d564.png)


Ghost Cars on spawns (no col):
![mta-screen_2023-02-12_17-33-57](https://user-images.githubusercontent.com/112903361/219026073-2348e66a-355d-40a9-a8b9-ec8e0660f918.png)
![mta-screen_2023-02-12_16-20-33](https://user-images.githubusercontent.com/112903361/219026079-1e6d9c94-ec61-417d-af49-d87f714ebc6f.png)
![mta-screen_2023-02-12_16-51-38](https://user-images.githubusercontent.com/112903361/219026087-e84c95ff-dc3c-4e01-810f-82898cbb52f4.png)


Vehicles in HAY ( Zero position problem ): 
![mta-screen_2023-02-10_19-58-56](https://user-images.githubusercontent.com/112903361/219027049-0675ebad-7f4d-40a3-9b61-8acfecb11458.png)

Random Power Race:
![mta-screen_2023-02-11_19-27-18](https://user-images.githubusercontent.com/112903361/219027856-c734d6bd-8968-4b1d-afa7-f50351ca3b1d.png)
![mta-screen_2023-02-10_10-32-36](https://user-images.githubusercontent.com/112903361/219027864-52b49f2c-fbca-4af7-bbcf-6f924e5f6950.png)

Spawn problems:
![mta-screen_2023-02-11_15-06-36](https://user-images.githubusercontent.com/112903361/219028085-8620b083-a90f-4833-a73a-414aafe3d4aa.png)

Red Light, Green Light wrong finish:
![mta-screen_2023-02-11_20-54-56](https://user-images.githubusercontent.com/112903361/219028222-221db689-1a12-474c-a3e0-02e79ff452ea.png)
![mta-screen_2023-02-10_17-59-13](https://user-images.githubusercontent.com/112903361/219028227-5c1615a4-f993-4f7b-9db4-7b71a63c1643.png)

**Comment by UPGyu** [comment]
**Sumo:**
After the countdown your vehicle changes randomly which works fine, but after you die and respawn you only get the vehicle used as spawnpoint on the map.

**Random Car Race and Random Power Care:**
After the map finished the votemode does not come up.

**Comment by UPGyu** [comment]
**/random cmd:**

One of the most important things to do is to remove the **/random** command, because someone always use it if they dont like the current game mode or if there a bug that prevents you from playing in the room. It would be best to fix this problem but if not possible then remove the command otherwise it will just cause more and more bugs.

So every time I go up to the server to test MG I always have to ask somebody to restart the MG room or i write down errors that dont normally happen, and its fucking annoying.
