### ISSUE TITLE
Bug: Dashboard/userpanel

### ISSUE THREAD

**Issue by xzihark** [MTASA-TFF/The-Favoured-Few#313]
Dashboard text is as presented on the screen. Also sometimes stickers disappear and I need to disable them as you can see on second screen then dashboard is getting fixed and I can see the stickers again.

![mta-screen_2023-02-15_13-56-04](https://user-images.githubusercontent.com/84672517/219038339-bc04366f-080b-4b85-b1bd-076263f6f922.png)
![mta-screen_2023-02-15_14-14-50](https://user-images.githubusercontent.com/84672517/219038350-88869e6c-0180-460b-a070-e8042bcac0e1.png)
![mta-screen_2023-02-15_14-17-59](https://user-images.githubusercontent.com/84672517/219038360-f21f543a-8b2f-40bf-8624-b09c2e2c8425.png)

**Comment by naouh** [comment]
This should be good now tell me if not :)

**Comment by xzihark** [comment]
> This should be good now tell me if not :)

Will let you know if it happen again
