### ISSUE TITLE
Bug: _Gyu_ - Bugged Lobby

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#314]
![mta-screen_2023-02-18_20-13-34](https://user-images.githubusercontent.com/112903361/219964223-9400a308-87e9-44c6-9e4b-7b1707d1b662.png)
![mta-screen_2023-02-18_20-13-44](https://user-images.githubusercontent.com/112903361/219964225-e9a09485-d96a-46b3-9a3e-bbd920a3e14a.png)

**Comment by naouh** [comment]
fixed already
