### ISSUE TITLE
Bug: persistent crashing on mta client side

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#317]
Issue opened by **El_Pinguino**

everytime i enter in the server anticheat shows as popup saying than there's not antivirus installed at anytime switching maps, as well hidden objects select to show sometimes the server doesn't reach that the option is activated   there's a connection issue where loading a new maps frooze you complitly on the download process, please fix

**Comment by naouh** [comment]
Seems like this issue come from your own internet provider try to restart ur internet box.
