### ISSUE TITLE
Bug: 2 Bugs i noticed

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#318]
Issue opened by **xDarkN**

1st , As i know , if ur in any arena and players amount is <= 3 you can buy anymap u want for 1$ and no cooldown. so in DM Hard it still gives Cooldown to the map
2nd , i received 1.1x Multipiler from opening a case few days ago and i noticed it works only on DM Classic .
Thanks in advance :)

**Comment by naouh** [comment]
1st: On hdm there is another system of cooldown it's normal,

2nd: i just tested if should be good when you activate a bonus of exp you need to reconnect (maybe this was the issue) ?
