### ISSUE TITLE
Enhancement: PDD Changes/Additions :)

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#393]
Issue opened by **ZUNII**

*New* 
Global Effect: Make every enemies vision blurry/drunk vision for 5-10 Seconds 
Global Effect: EMP, deactivates every enemies Engine (can not accelerate anymore for 3-5 Seconds) 
Time Machine (Can be used 2x to set rewind points / restore Health / nos etc to the point when used first) 
Change Positions: Change Positions with a random Person (alternative: hit an enemy before, after that you can change positions with him within 10secs) 
Reversed Controls: Gives an enemy reversed controls 
Shell: Shoot an projectile which stumbles the enemy (hits with a little recoil so he looses a bit of control) 
Steal PowerUp: Steal one random power up from an enemy 
Ramp Ca

**Comment by ZUNII** [comment]
Whole Text

*New*
Global Effect: Make every enemies vision blurry/drunk vision for 5-10 Seconds
Global Effect: EMP, deactivates every enemies Engine (can not accelerate anymore for 3-5 Seconds)
Time Machine (Can be used 2x to set rewind points / restore Health / nos etc to the point when used first)
Change Positions: Change Positions with a random Person (alternative: hit an enemy before, after that you can change positions with him within 10secs)
Reversed Controls: Gives an enemy reversed controls
Shell: Shoot an projectile which stumbles the enemy (hits with a little recoil so he looses a bit of control)
Steal PowerUp: Steal one random power up from an enemy
Ramp Car?: spawn a waterjump infront of your car and it sticks to your car for 6 Seconds, like that one gta 5 ramp car
Launch Pad: Drop a mine behind you that launches any one who drives over it into the air and spins you (like an explosion(same decay speed as oil or spikes))

*Rework*
Timewarp: Hit Enemy and increase his gamespeed
Shield: Block all powerups until hit with one (can not stack)
Laser: Add a second Laser to the car (double the damage)
Ignite: Increase Damage (Burn 15-20% max health)

*Remove*
Invisibility: Useless, easy to counter, can see lights, no profit

ZUNII, Torque, Kaziko, btnd
