### ISSUE TITLE
Car Bug

### ISSUE THREAD

**Issue by Lolikaaa** [MTASA-TFF/The-Favoured-Few#409]
Hello TFF developers
Last days we have really bad issue about infernus. When you hit to something

https://github.com/MTASA-TFF/The-Favoured-Few/assets/155254796/3badc32e-dfe9-494c-bc48-7c867c054934

 with between 200-221 speed my infernus disaappered.Wff has wall bounces a lot so its very annoying and it decrease our gameplay. In video i already hitted part and my infernus broken and sometimes its disappered, more than this. I hıpe we can solve it as soon as possible.

**Comment by naouh** [comment]
Will replace this model asap, until enable bodyparts so you use tff infernus

**Comment by naouh** [comment]
pushed this morning
