### ISSUE TITLE
WFF CW BUG

### ISSUE THREAD

**Issue by Lolikaaa** [MTASA-TFF/The-Favoured-Few#412]
Hey Developers
Since 1 month ago we have some issues in wff cw which one dont let us play that cw type.
Generally Cw stuck on 1 map and it keep setting the same map whole 20 map.
2nd issue, there is something wrong about point system, its giving points too random.Also when noone finished the map, system is giving points to random players.tff has good system about showing % progress on map how long you finished the map.It could be nice to optimize that system with WFF cw then who go further could get more points.

Wish you all good works

**Comment by naouh** [comment]
fixed progress was not loaded correctly, rounds are working fine
