### ISSUE TITLE
bug after another map start

### ISSUE THREAD

**Issue by Tickz0r** [MTASA-TFF/The-Favoured-Few#417]
this has been happening for a while now, simply when the map ends and another one loads, i cant play the other map, and my ping goes up to 700~800

**Comment by Tickz0r** [comment]
![mta-screen_2024-02-12_10-19-45](https://github.com/MTASA-TFF/The-Favoured-Few/assets/36250944/b6b13d08-080e-4b4c-9f6c-7d57920541ec)

**Comment by naouh** [comment]
can't do anything must be net issue
