### ISSUE TITLE
Enhancement: powers

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#430]
Issue opened by **Nao**

remove reverse shit and add thief and some other ?

**Comment by UPGyu** [comment]
**Reverse**:

Reverse power isnt that bad in my opinion if the script works perfectly. Players need a little brain how to use it correctly...
But, there could be a variation where it doesnt just reverse the opponent by 180 degrees but rotates them randomly by 360 degrees, allowing for anything to happen. For example, if your opponent touches you, they could rotate by 90 or 45 degrees, etc."



**New Powers:**


**1. Teleport:**
	 While you using the power and you change your car with default race pickup its give you back your previous vehicle so palyers cant abuse with shitty Dune or other pickups...

**2. Portal:**
	This power works by creating a blue marker behind you, then you have 5 seconds to create an orange marker again. If you run out of time, it will create a orange marker on its own. If you go into the blue one, you spawn into the orange one, or vice versa.

**3. Flip Screen:**
	If you hit your opponent, the screen turns upside down for 5 seconds.

**4. Kamikaze:**
	If you activate the kamikaze power and touch your opponent, you will both die.

**5. Mine:**
	Spawn a kmb_mine object behind your vehicle.[ ID: 2918 ] --- If your opponent hits it with large vehicles at high speed, it will fly away.( If everything alright )

**6. FunnyWall:**
	Spawn a kmb_netting object behind your vehicle.[ ID: 2945 ] --- Similar with the kmb_mine object just another model. ( If everything alright )

**7. Hay:**
	Spawn a SW_haybreak02 object behind your vehicle.[ ID: 3374 ] 

**8. Gangster:**
	You get a UZI weapon and you can shoot it for 5 seconds.

**9. Spy:**
	Special Power for only Team Event or ClanWars. Your Nametag and Vehicle will be the same color as your opponents team.
	( The team name can remain your own but the color will change to your opponents. )

**10. Fake:**
	Spawn Fake Power behind your vehicle. Whoever picks it up gets nothing. Only a clown emoji appears large on the screen and there is loud laughter for 5 seconds.

**11. Trap:**
	You spawn Trap Power behind your vehicle and whoever picks it up instant jump or spin etc. gets some negative power.

**12. Parking:**
	If you touch your opponent, he must stop his vehicle because if he keeps moving he loses health.

**13. Engine:**
	If you touch your opponent, the engine of his vehicle will shut down for 5 sec. --- In this state it is easier to push his vehicle.

**14. Mother-in-law:**
	If you touch your opponent, he will be moved to the Mother-in-law seat for 5 seconds. --- In this state he cant control his vehicle.

**15. Bike:**
	You get a random bike vehicle: [ ID: 448, 461, 462, 463, 468, 471, 521, 522, 523, 581, 586 ] --- I want this because by default, Bikes are deleted later.

**16. Baseball:**
	Spin yourself 360° 5x times, then return original position ( or not ).

**17. Rat:**
	You get an RC Tiger [ ID: 564 ] for 3 seconds, then you get your previous vehicle back.

**18. Lucky7:**
	You will randomly get one vehicle from Baggage, Sweeper, Forklift, Mower, Tug, Caddy, Kart or Dumper.
	[ ID: 485, 574, 530, 572, 583, 457, 571 or 406 ]

**19. Forklift:**
	If you touch your opponent, his vehicle will turn like a forklift.

**20. Camouflage:**
	Your vehicle is covered by bushes so your opponents cant see what kind of vehicle you have.

**21. Hypnosis:**
	The "scale" of all the objects on the map goes minus and plus randomly for 5sec.

**22. Tron:**
	You draw a line behind your vehicle, and if your opponents run into it, they lose health.

**Comment by naouh** [comment]
removed reverse control for now until adding new powers
