### ISSUE TITLE
Bug: pdd ghost

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#432]
Issue opened by **Nao**

Cant pass through allies only ennemies

**Comment by UPGyu** [comment]
Please dont, with Ghost Power it would be the best decision to change the power so that it can go through players placed objects like Oil, Barrel, Ramp, Car Ramp, Rocket, etc.

**Comment by UPGyu** [comment]
The **Invisible** Power can be such that team members can see it, but the opponent team members cant.
