### ISSUE TITLE
Bug: pdd 1 vs 1 winner 

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#435]
Issue opened by **Nao**

still doesnt work player with less hp not always winning

**Comment by naouh** [comment]
fixed maybe ?

**Comment by UPGyu** [comment]
Idk if this updated but bug just happened now in event.

![mta-screen_2024-05-01_00-57-15](https://github.com/MTASA-TFF/The-Favoured-Few/assets/112903361/1164dfd5-c1eb-4b78-8f62-3157e60ea7f9)
![mta-screen_2024-05-01_00-57-22](https://github.com/MTASA-TFF/The-Favoured-Few/assets/112903361/0fd92bca-847d-4404-83f3-6e0e1f64449f)
