### ISSUE TITLE
Bug: PDD Magnet

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#451]
**Magnet and Car Ramp:**
If you catch someone with magnet while your opponent is using a car ramp, you both go flying cuz the ramp lifts the player who using magnet.

**Magnet and 0 position bug:**
If your opponent catches you with a magnet and he dies but you dont, you will teleport to position 0 in GTA map.

**Magnet and Laser:**
If you catch your opponent who using a laser, the position of his vehicle and the laser will not match.
_( Not a big thing, but the other two is serious problem. )_

**Comment by naouh** [comment]
fixed already
