### ISSUE TITLE
Enhancement: min FPS and max PING in PDD room

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#452]
It would be really nice to set a min FPS and max PING cuz its boring to see some fuckers trying to play with high or 5000+ ping.

min FPS: 30
max PING: 500

Another Enhancement: It would be cool if set the max FPS from 50-51 to 60-61 in PDD rooms.

**Comment by naouh** [comment]
Idk about fps yet but rest wont add
