### ISSUE TITLE
Bug: PDD Oil And Custom Vehicles

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#459]
![mta-screen_2024-06-11_23-49-23](https://github.com/MTASA-TFF/The-Favoured-Few/assets/112903361/619c8676-37da-4f38-aff1-d23a5422b0eb)

![mta-screen_2024-06-11_22-04-55](https://github.com/MTASA-TFF/The-Favoured-Few/assets/112903361/ab3198cf-5740-4597-ad1d-fe2268f1d7cf)

![mta-screen_2024-06-11_22-14-39](https://github.com/MTASA-TFF/The-Favoured-Few/assets/112903361/e547aae2-3a16-4438-b2f7-7176e2d386d1)

![mta-screen_2024-06-11_23-07-43](https://github.com/MTASA-TFF/The-Favoured-Few/assets/112903361/f42e8c49-7d3b-4b67-b718-133a73354b0b)

**Comment by naouh** [comment]
fixed

**Comment by UPGyu** [comment]
Custom vehicles not started after server restart? Its not works again.
