### ISSUE TITLE
Bug: Interface bug

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#464]
Issue opened by **ZUNII**

Im using Interface and Speedotype "2".

Map name is on the bottom right under the nos gauge with a weird "low res" font.

**Comment by ZUNII** [comment]
![9JGe2Ri](https://github.com/MTASA-TFF/The-Favoured-Few/assets/50987498/2e58931b-b894-41ac-b185-1c19d288dde5)
