### ISSUE TITLE
Bug: PDD gamemode

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#471]
Issue opened by **veni**

If you're using your power and kill someone without touching his car with ur car you won't get a point for getting that kill. Should be fixed. Another big issue is that some players abusing disconnecting before they die and the player that killed that guy doesn't get the point for the kill that he made.

**Comment by UPGyu** [comment]
https://github.com/MTASA-TFF/The-Favoured-Few/issues/466
https://github.com/MTASA-TFF/The-Favoured-Few/issues/458

**Comment by SkreePy18** [comment]
Duplicated...
