### ISSUE TITLE
Bug: PDD Vehiclechanger Marker Not Works

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#482]
On some maps, for some reason, the vehiclechanger marker is not marked on the radar and does not work. These worked well at yesterdays events.

![mta-screen_2024-07-19_23-07-47](https://github.com/user-attachments/assets/b1c463b7-2a28-4053-8f79-09a50762e238)

![mta-screen_2024-07-19_21-48-08](https://github.com/user-attachments/assets/6f51d4b4-2878-4994-ac21-81813a60d70f)

![mta-screen_2024-07-19_22-55-48](https://github.com/user-attachments/assets/955cd52b-6a8b-4841-8542-83e570e9a052)

**Comment by naouh** [comment]
to be uploaded
