### ISSUE TITLE
Bug: PowerDD Random teamkill at the beginning

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#485]
Issue opened by **Maybe**

I got 3 kills randomly without touching anyone at the beginning of the round.
Here's a video of it: https://www.youtube.com/watch?v=As7hXn1HlTU

I have no clue how or why it happened. Same thing happened next round again with a teamkill.

**Comment by UPGyu** [comment]
Similar happened to me when i touched my own ramp and i died, it indicated that someone else killed me.

**Comment by UPGyu** [comment]
https://github.com/MTASA-TFF/The-Favoured-Few/issues/466
