### ISSUE TITLE
Bug: Arrow Marker Type VehicleChanger Not Works In PDD

### ISSUE THREAD

**Issue by UPGyu** [MTASA-TFF/The-Favoured-Few#488]
On the radar marked but your vehicle not changed
Other marker types tested and works

![mta-screen_2024-07-30_21-16-46](https://github.com/user-attachments/assets/9aea48c0-a5db-4305-a637-2055878ce198)

**Comment by SkreePy18** [comment]
The marker placement is not correct. The arrow is too high, and because of this, markerHit event is not triggered, only with Dumper..

Either you put it more below, or replace the marker type.
