### ISSUE TITLE
Bug: ancient chest

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#492]
Issue opened by **Davidsky**

got ancient chest, opened it got 10 garage coins, didnt get them.
i dont want them just fix it

**Comment by naouh** [comment]
will take a look

**Comment by naouh** [comment]
It work you need to go in items and reedem them:

![image](https://github.com/user-attachments/assets/8378ff51-4599-4770-bbab-63a2a02c10cc)
