### ISSUE TITLE
Enhancement: disable horn in the game

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#498]
Issue opened by **NaGaFo**

There are just a lot of individuals who are bind horn to nitro key.
for example: setWorldSoundEnabled(17,false) -- 17 is horn id
This is very annoying. Thx

**Comment by nagafo** [comment]
https://wiki.multitheftauto.com/wiki/SetWorldSoundEnabled

**Comment by naouh** [comment]
to be uploaded
