### ISSUE TITLE
Bug: Color Gradients 

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#501]
Issue opened by **Sonn**

Hey i wanted to request color changing car gradients which u can choose ur self, for example add multiple colors like, green blue white, and rainbow color etc, for the entire car, just like leds, and talking about leds, like under the car leds would be fire too

**Comment by SkreePy18** [comment]
Due to the excess calculation required for the shader to use custom colors, we have decided to use predefined images to avoid creating more performance-demanding features. You can create gradient pictures just as you see in the garage, send them to us, and we will consider adding them.
