### ISSUE TITLE
Bug: challenge other player while event

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#505]
Issue opened by **Maybe**

If theres an event and you have a challenge against another player, you lose the battle when u reach the hunter frist, because u get killed instantly. It should be changed for when theres an event that the first player to reach hunter wins the challenge

**Comment by SkreePy18** [comment]
Due to the excess calculation required for the shader to use custom colors, we have decided to use predefined images to avoid creating more performance-demanding features. You can create gradient pictures just as you see in the garage, send them to us, and we will consider adding them.
