### ISSUE TITLE
Bug: Events rewards

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#512]
Issue opened by **Kamen**

When 2 or more players are on euqal points in the daily events in the top 3, random winners are being picked up which is a bit disappointing and infair for the ones that are lefts out
example: WFF event
Condom 20pts - 1st
Neonox 18 pts- 2nd
No1se 15pts - 3rd (random winner)
Geass 15 pts - 4th ( no reward)
Equinox 15pts - 5th (no reward)

**Comment by naouh** [comment]
to be uploaded

**Comment by naouh** [comment]
![image](https://github.com/user-attachments/assets/816561a0-0aca-4ba1-93d0-e7cc4a7e2444)

**Comment by naouh** [comment]
Also fixed clan constructor at event end to rebuild real clans

**Comment by naouh** [comment]
Players who played less than 5 rounds of event wont get rewards unless they are MVP
