### ISSUE TITLE
Visual issue: TemptatioN - Screen Freezing while in gameplay that causes random drift

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#57]
I've tried to disable (overlay,stickers,etc...) all those things that could eventually cause any kind of lag/freezing, restarted PC, overclocked GPU, I gave HIGH PRIORITY to MTA in the Task Manager... nothing solved, before when there were not that many players, at the very beggining it wasn't happening, but after some 'updates' I think that was the cause of those Screen Freezing for me... I have powerfull PC for MTA, this should not being happening, is there any solution for this?

**Comment by SkreePy18** [comment]
This was most probably caused by clan wars, we have fixed that issue.
