### ISSUE TITLE
Idea/request: kappa27 - my trash ideas xD

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#78]
map progress bar, buy redo , server recording ur run on maps , !roll , stuntage arena, and og tff Anti bounce script cuz mta 2022 = only retarded bounces xDDD

**Comment by UPGyu** [comment]
**Map Progress Bar:**
_https://community.multitheftauto.com/index.php?p=resources&s=details&id=586
https://community.multitheftauto.com/index.php?p=resources&s=details&id=13957_


**Car Replay Playback - Recording**
_https://community.multitheftauto.com/index.php?p=resources&s=details&id=18690
https://community.multitheftauto.com/index.php?p=resources&s=details&id=7790
https://community.multitheftauto.com/index.php?p=resources&s=details&id=3585
https://community.multitheftauto.com/index.php?p=resources&s=details&id=563
https://community.multitheftauto.com/index.php?p=resources&s=details&id=461_

**Comment by naouh** [comment]
We will see later for this map progress , buy redo is not planned same as replay, antibounce big no :D
